hotel:
  hotel_name: "hotel_1"
  device_list: ["101_life_being", "101_iaq_sensor","102_life_being", "102_iaq_sensor"]
mongodb: 
  hostname: 'localhost'
  port: 27017
  dbName: 'alto'
mqtt:
  hostname: '167.172.90.42'
  port: 1883
  username: 'mydevice'
  password: '9123900000' 
server:
  hostname: 'localhost'
  port: 8080